###### Authentication ######

### 01 Signup
POST http://localhost:5000/api/v1/auth/signup
Content-Type: application/json

{
    "firstName": "Praveen",
    "lastName": "Ande",
    "email": "praveen@example.com",
    "password":"praveen123",
    "roleId":"5c4730e8-1e17-4daf-8a12-b8c5433671b8"
}

### 02 Signin
POST http://localhost:5000/api/v1/auth/signin
Content-Type: application/json

{
  "email": "praveen@example.com",
  "password": "praveen123"
}

### 03 Signout

@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0OWM2YjUyMS1iZDljLTQ0YmItYWM0NC02NTI0NDNkODk5ZmIiLCJpYXQiOjE3MzI3MTgyNDMsImV4cCI6MTczMzMyMzA0M30.zBpq1WSmkt-Tv0XKcwLC_ZAI2utXl4GkGPONhA_v4Yo
GET http://localhost:5000/api/v1/auth/signout
Cookie: refreshToken={{refreshToken}}

### 04 verifyToken
GET http://localhost:5000/api/v1/auth/verify-token
Cookie: refreshToken={{refreshToken}}


